import { notFound } from 'next/navigation';
import { requireChatGPTUser } from '@/app/chatgpt-auth';
import { PortalHeader } from '@/components/PortalHeader';
import { UploadPanel } from '@/components/UploadPanel';
import { ReviewControls } from '@/components/ReviewControls';
import { getProjectBundle,isStudioAdmin } from '@/lib/data';
import { fileSize,shortDate,titleCase } from '@/lib/format';
export const dynamic='force-dynamic';
export default function ProjectPage({params}:{params:Promise<{id:string}>}){return <ProjectContent params={params}/>}
async function ProjectContent({params}:{params:Promise<{id:string}>}){const{id}=await params;const user=await requireChatGPTUser(`/portal/projects/${id}`);const bundle=await getProjectBundle(id,user);if(!bundle)notFound();const admin=isStudioAdmin(user.email);const canDecide=bundle.project.owner_id===user.userId;const seeds=bundle.assets.filter(a=>a.kind==='seed');const reviews=bundle.assets.filter(a=>a.kind==='review');const deliveries=bundle.assets.filter(a=>a.kind==='deliverable');return <main className="portal-page"><PortalHeader user={user}/><section className="project-banner"><div className="shell"><a className="back-link" href="/portal">← All projects</a><div className="project-title-grid"><div><p className="eyebrow"><span>●</span> {titleCase(bundle.project.project_type)}</p><h1>{bundle.project.title}</h1><p>{bundle.project.brief}</p></div><div className="project-facts"><div><span>Status</span><strong>{titleCase(bundle.project.status)}</strong></div><div><span>Target date</span><strong>{shortDate(bundle.project.due_date)}</strong></div><div><span>Formats</span><strong>{JSON.parse(bundle.project.aspect_ratios||'[]').join(', ')||'To confirm'}</strong></div></div></div></div></section><section className="project-content"><div className="shell project-layout"><aside><nav className="project-nav"><a href="#overview">Overview</a><a href="#seeds">Seed library <b>{seeds.length}</b></a><a href="#review">Review queue <b>{reviews.length}</b></a><a href="#delivery">Delivery <b>{deliveries.length}</b></a></nav><div className="brief-card"><span>Client</span><strong>{bundle.project.owner_email}</strong><span>Audience</span><p>{bundle.project.audience||'Not specified'}</p><span>Platforms</span><p>{bundle.project.platforms||'Not specified'}</p><span>Style direction</span><p>{bundle.project.style_notes||'Not specified'}</p></div></aside><div className="project-sections"><section id="overview" className="portal-card"><div className="card-heading"><div><span>UPLOADS</span><h2>{admin?'Add work for review':'Build the seed library'}</h2></div></div><UploadPanel projectId={id} isAdmin={admin}/></section><AssetSection title="Image seeds" id="seeds" empty="No seed images have been added yet." assets={seeds} comments={bundle.comments} projectId={id} canDecide={false}/><AssetSection title="Review queue" id="review" empty={admin?'Upload a review version when it is ready for the client.':'Nothing needs your review right now.'} assets={reviews} comments={bundle.comments} projectId={id} canDecide={canDecide}/><AssetSection title="Final delivery" id="delivery" empty="Approved delivery files will appear here." assets={deliveries} comments={bundle.comments} projectId={id} canDecide={canDecide}/></div></div></section></main>}
function AssetSection({title,id,empty,assets,comments,projectId,canDecide}:{title:string;id:string;empty:string;assets:import('@/lib/data').StudioAsset[];comments:import('@/lib/data').StudioComment[];projectId:string;canDecide:boolean}){return <section id={id} className="portal-card"><div className="card-heading"><div><span>{String(assets.length).padStart(2,'0')} FILES</span><h2>{title}</h2></div></div>{assets.length===0?<p className="empty-line">{empty}</p>:<div className="asset-grid">{assets.map(asset=><article className="asset-card" key={asset.id}><div className="asset-media">{asset.mime_type.startsWith('video/')?<video controls preload="metadata" src={`/api/files/${asset.id}`}/>:<img src={`/api/files/${asset.id}`} alt={asset.label||asset.filename}/>}<span className={`asset-status ${asset.status}`}>{titleCase(asset.status)}</span></div><div className="asset-info"><div><span>{titleCase(asset.kind)} · V{asset.version}</span><strong>{asset.label||asset.filename}</strong><small>{fileSize(asset.byte_size)} · {shortDate(asset.created_at)}</small></div><a href={`/api/files/${asset.id}`} target="_blank" rel="noreferrer">Open ↗</a></div>{comments.filter(c=>c.asset_id===asset.id).length>0&&<div className="comment-list">{comments.filter(c=>c.asset_id===asset.id).map(c=><div key={c.id}><strong>{c.author_email}</strong><p>{c.body}</p><small>{shortDate(c.created_at)}</small></div>)}</div>}{asset.kind!=='seed'&&<ReviewControls projectId={projectId} assetId={asset.id} canDecide={canDecide}/>}</article>)}</div>}</section>}
