import Link from 'next/link';
import type { Metadata } from 'next';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { SiteHeader } from '@/components/SiteHeader';
import { SiteFooter } from '@/components/SiteFooter';
import { getCreatorApplicationForUser,listPublicCreators } from '@/lib/data';

export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Inchframe Studio Partners',description:'Find a vetted video production partner for your next project, or apply as an eligible paid Pro member to join the Inchframe Studio Partner network.'};
const benefits=[
  {code:'01',title:'Choice for clients',copy:'Browse approved production profiles, specialties, sample work, rate ranges, and availability—or ask Inchframe to recommend the right fit.'},
  {code:'02',title:'One managed project',copy:'Inchframe keeps matching, scope, pricing, client communication, reviews, payment, and final delivery inside one accountable workspace.'},
  {code:'03',title:'Opportunity for Partners',copy:'Eligible paid Pro members can present their strengths and respond to qualified private work without publishing personal contact details.'}
];
const steps=[
  ['01','Confirm Paid Pro','Sign in with an active Inchframe Paid Pro account to confirm Partner eligibility.'],
  ['02','Apply for review','Submit your production profile, rate range, availability, and selected external work links.'],
  ['03','Complete verification','Inchframe reviews membership, identity, tax details, payout readiness, and production fit.'],
  ['04','Work through Studio','Approved partners can receive direct requests and access private Pro Studio opportunities.']
];
export default async function StudioPartnersPage(){
  const user=await getChatGPTUser();
  const [creators,profile]=await Promise.all([listPublicCreators(),user?getCreatorApplicationForUser(user):Promise.resolve(null)]);
  const partnerEntryHref=profile?'/portal/studio-partners':'/api/auth/account/start?returnTo=%2Fportal%2Fstudio-partners&intent=studio_partner';
  const partnerEntryLabel=profile?'Open your Partner dashboard →':'Continue with Inchframe Account →';
  return <main><SiteHeader/>
    <section className="page-hero creator-directory-hero"><div className="shell"><p className="eyebrow"><span>●</span> Inchframe Studio Partner Network</p><h1>Find your production<br/><em>partner. Or become one.</em></h1><p className="hero-lede">Clients get a managed way to find the right production specialist for the brief. Eligible paid Pro members can apply to join the growing network, build a public production profile, and receive qualified opportunities through Inchframe.</p><div className="hero-actions">{profile?<><a className="button button-green" href={partnerEntryHref}>{partnerEntryLabel}</a><a className="button button-outline" href="#directory">Browse Studio Partners ↓</a></>:<><a className="button button-green" href="#directory">Browse Studio Partners ↓</a><a className="button button-outline" href={partnerEntryHref}>{partnerEntryLabel}</a></>}</div><div className="trust-line"><span>Vetted production profiles</span><i/><span>Private project matching</span><i/><span>Inchframe-managed work</span></div></div></section>
    <section className="signal-strip"><div className="shell signal-inner"><span>Music + artist visuals</span><b>×</b><span>Brand + product films</span><b>×</b><span>Launch + social content</span><b>×</b><span>Directed AI production</span></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow"><span>●</span> One network, two clear paths</p><h2>More production range.<br/><em>One accountable Studio.</em></h2><p>Clients can compare specialists or let Inchframe route the brief. Studio Partners get a professional channel for qualified work. Inchframe keeps the relationship and production record organized for both sides.</p></div><div className="service-grid">{benefits.map(item=><article className="service-card" key={item.code}><span className="card-code">{item.code}</span><div><h3>{item.title}</h3><p>{item.copy}</p></div><small>INCHFRAME STUDIO NETWORK</small></article>)}</div></div></section>
    <section className="section client-section"><div className="shell creator-network-panel"><div><p className="eyebrow"><span>●</span> For clients</p><h2>One brief.<br/><em>More ways to make it.</em></h2><p>Explore a growing roster of independent production specialists with different strengths, styles, rates, and availability. Request a specific Studio Partner or submit the brief privately and let Inchframe recommend the production path.</p><div className="hero-actions"><a className="button button-green" href="#directory">Browse the directory ↓</a><Link className="button button-outline" href="/register">Start a client project →</Link></div></div><div className="creator-benefits"><span>PRODUCTION STRENGTHS</span><strong>Music videos + artist visuals</strong><strong>Brand + product films</strong><strong>Launch clips + social cutdowns</strong><strong>Narrative shorts + visual stories</strong><strong>Motion, compositing + finishing</strong><p>Approved profiles show real specialties and external work samples. Availability and project fit are confirmed before production begins.</p></div></div></section>
    <section className="section" id="requirements"><div className="shell creator-network-panel"><div><p className="eyebrow"><span>●</span> For Partner candidates</p><h2>Set the project price.<br/><em>Know the split.</em></h2><p>Studio Partners set a customer-facing price at or above the applicable minimum. When a customer funds a Studio Partner project, Inchframe retains 20% of the service price. Payment-processing, Connect, and payout fees are deducted from partner compensation.</p><p>Studio Partners participate as independent contractors and remain responsible for their own taxes, insurance, tools, and legal obligations. Project scope, milestones, revisions, communication, approvals, and final delivery are recorded inside Studio.</p><div className="hero-actions"><a className="button button-green" href={partnerEntryHref}>{partnerEntryLabel}</a></div></div><div className="creator-benefits"><span>REQUIREMENTS TO APPLY</span><strong>Active paid Inchframe Pro membership</strong><strong>Independent-contractor eligibility</strong><strong>Identity verification</strong><strong>Tax and payout readiness</strong><strong>Client contact kept inside Studio</strong><strong>Production profile approved by Inchframe</strong><p>Start through your Inchframe Account. Approval is selective and does not guarantee assignments, project volume, or earnings.</p></div></div></section>
    <section className="section process-section"><div className="shell"><div className="section-heading"><p className="eyebrow"><span>●</span> The partner path</p><h2>From Paid Pro<br/><em>to production-ready.</em></h2></div><div className="process-grid">{steps.map(([number,title,copy])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section" id="directory"><div className="shell"><div className="section-heading"><p className="eyebrow"><span>●</span> Studio Partner Directory</p><h2>A growing roster.<br/><em>Private introductions.</em></h2><p>Review approved production profiles and request a specific Studio Partner, or ask Inchframe to route your brief to the right fit. Pricing, contact, and project communication remain inside Studio.</p></div>{creators.length===0?<div className="empty-state"><span>PARTNER 00</span><h2>Studio Partner reviews are underway.</h2><p>The first approved Studio Partners will appear here. You can still submit a client brief and ask Inchframe to recommend the production route.</p><Link className="button button-green" href="/register">Start a client project →</Link></div>:<div className="creator-grid">{creators.map(creator=><Link className="creator-card" href={`/studio-partners/${creator.slug}`} key={creator.id}><img src={`/api/creator-icons/${creator.id}`} alt=""/><div><span className="card-code">INCHFRAME STUDIO PARTNER</span><h2>{creator.display_name}</h2><strong>{creator.headline}</strong><p>{creator.location} · {creator.availability}</p><small>{creator.specialties}</small></div><b aria-hidden="true">→</b></Link>)}</div>}</div></section>
    <section className="section final-cta"><div className="shell cta-panel"><p className="eyebrow"><span>●</span> Choose your side of the network</p><h2>Need a specialist?<br/><em>Ready to be one?</em></h2><p>Clients can start with a private brief. Eligible paid Pro members can continue through Inchframe Account to enter the Studio Partner review process.</p><div className="hero-actions"><Link className="button button-green" href="/register">Start a client project →</Link><a className="button button-outline" href={partnerEntryHref}>{partnerEntryLabel}</a></div></div></section>
    <SiteFooter/>
  </main>;
}
