import Link from 'next/link';
import type { Metadata } from 'next';
import { SiteHeader } from '@/components/SiteHeader';
import { SiteFooter } from '@/components/SiteFooter';
import { listPublicCreators } from '@/lib/data';

export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Inchframe Studio Partners',description:'Apply to join Inchframe Pro Studio or meet vetted Studio Partners available for Inchframe-led productions.'};
const benefits=[
  {code:'01',title:'Private opportunities',copy:'Review qualified Pro Studio briefs and submit your customer-facing price, timing, and scope privately.'},
  {code:'02',title:'One production desk',copy:'Inchframe handles discovery, client access, payment, project records, reviews, and final delivery in one workspace.'},
  {code:'03',title:'A public production profile',copy:'Present your strengths, rate range, availability, profile icon, and up to five external work samples without publishing personal contact details.'}
];
const steps=[
  ['01','Confirm Paid Pro','Generate a Studio Partner invitation from an active Inchframe Paid Pro account.'],
  ['02','Apply for review','Submit your production profile, rate range, availability, and selected external work links.'],
  ['03','Complete verification','Inchframe reviews membership, identity, tax details, payout readiness, and production fit.'],
  ['04','Work through Studio','Approved partners can receive direct requests and access private Pro Studio opportunities.']
];
export default async function StudioPartnersPage(){
  const creators=await listPublicCreators();
  return <main><SiteHeader/>
    <section className="page-hero creator-directory-hero"><div className="shell"><p className="eyebrow"><span>●</span> Inchframe Pro Studio</p><h1>Join the production<br/><em>side of Inchframe.</em></h1><p className="hero-lede">Studio Partners are independent video professionals who work through Inchframe on qualified client productions. Paid Pro members can apply for a public profile and private project opportunities.</p><div className="hero-actions"><Link className="button button-green" href="/studio-partners/apply">Become a Studio Partner →</Link><a className="button button-outline" href="#directory">Meet Studio Partners</a></div><div className="trust-line"><span>Paid Pro eligibility</span><i/><span>Private opportunities</span><i/><span>Inchframe-managed production</span></div></div></section>
    <section className="signal-strip"><div className="shell signal-inner"><span>Qualified briefs</span><b>×</b><span>Private pricing</span><b>×</b><span>Recorded approvals</span><b>×</b><span>Managed payment</span></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><p className="eyebrow"><span>●</span> What partners receive</p><h2>Your work.<br/><em>One managed channel.</em></h2><p>Inchframe brings the client, production workflow, and commercial structure together so the work can stay focused and accountable.</p></div><div className="service-grid">{benefits.map(item=><article className="service-card" key={item.code}><span className="card-code">{item.code}</span><div><h3>{item.title}</h3><p>{item.copy}</p></div><small>INCHFRAME PRO STUDIO</small></article>)}</div></div></section>
    <section className="section client-section"><div className="shell creator-network-panel"><div><p className="eyebrow"><span>●</span> Clear commercial terms</p><h2>Set the project price.<br/><em>Know the split.</em></h2><p>Studio Partners set a customer-facing price at or above the applicable minimum. When a customer funds a Studio Partner project, Inchframe retains 20% of the service price. Payment-processing, Connect, and payout fees are deducted from partner compensation.</p><p>Studio Partners participate as independent contractors and remain responsible for their own taxes, insurance, tools, and legal obligations. Project scope, milestones, revisions, communication, approvals, and final delivery are recorded inside Studio.</p><div className="hero-actions"><Link className="button button-green" href="/studio-partners/apply">Apply for review →</Link></div></div><div className="creator-benefits"><span>PARTNER ELIGIBILITY</span><strong>Active Inchframe Paid Pro membership</strong><strong>Identity verification</strong><strong>Tax and payout readiness</strong><strong>Production profile approved by Inchframe</strong><p>Approval is selective and does not guarantee assignments, project volume, or earnings.</p></div></div></section>
    <section className="section process-section"><div className="shell"><div className="section-heading"><p className="eyebrow"><span>●</span> The partner path</p><h2>From Paid Pro<br/><em>to production-ready.</em></h2></div><div className="process-grid">{steps.map(([number,title,copy])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section" id="directory"><div className="shell"><div className="section-heading"><p className="eyebrow"><span>●</span> Studio Partner Directory</p><h2>Vetted partners.<br/><em>Private introductions.</em></h2><p>Clients can request a specific Studio Partner or ask Inchframe to route the project. Pricing, contact, and project communication remain inside Studio.</p></div>{creators.length===0?<div className="empty-state"><span>PARTNER 00</span><h2>Studio Partner reviews are underway.</h2><p>The first approved Studio Partners will appear here.</p><Link className="button button-green" href="/studio-partners/apply">Become a Studio Partner →</Link></div>:<div className="creator-grid">{creators.map(creator=><Link className="creator-card" href={`/studio-partners/${creator.slug}`} key={creator.id}><img src={`/api/creator-icons/${creator.id}`} alt=""/><div><span className="card-code">INCHFRAME STUDIO PARTNER</span><h2>{creator.display_name}</h2><strong>{creator.headline}</strong><p>{creator.location} · {creator.availability}</p><small>{creator.specialties}</small></div><b aria-hidden="true">→</b></Link>)}</div>}</div></section>
    <section className="section final-cta"><div className="shell cta-panel"><p className="eyebrow"><span>●</span> Paid Pro member?</p><h2>Bring your production<br/><em>strengths to Studio.</em></h2><p>Use your Inchframe Studio Partner invitation to apply. Personal contact details stay private and work is coordinated through Inchframe.</p><Link className="button button-green" href="/studio-partners/apply">Start your application →</Link></div></section>
    <SiteFooter/>
  </main>;
}
