'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { ProjectAgreement } from '@/lib/data';

type Viewer='client'|'creator'|'admin';
const fallback={goal:'',scope:'',deliverables:'',out_of_scope:'',start_date:'',target_date:'',milestones:'',revision_rounds:1,response_expectation:'Respond within two business days',client_responsibilities:'Provide accurate source materials, consolidated feedback, and approvals on schedule.',creator_responsibilities:'Produce the agreed work, post regular updates, flag blockers promptly, and protect client materials.',final_delivery:'Approved master file plus the formats listed in the agreement, delivered through this private project.',change_policy:'Changes outside the agreed scope require a written change request and may change price or timing.'};

export function ProductionAgreement({projectId,agreement,viewer,defaultGoal,defaultTargetDate}:{projectId:string;agreement:ProjectAgreement|null;viewer:Viewer;defaultGoal:string;defaultTargetDate:string|null}){
  const router=useRouter(),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[note,setNote]=useState('');
  const current=agreement||{...fallback,goal:defaultGoal,target_date:defaultTargetDate||''};
  const editable=viewer==='creator'&&(!agreement||['draft','changes_requested'].includes(agreement.status));
  async function request(payload:Record<string,unknown>){setBusy(String(payload.action));setMessage('');try{const response=await fetch(`/api/projects/${projectId}/agreement`,{method:'POST',credentials:'include',cache:'no-store',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(result.error||'Could not update the agreement.');setMessage(result.message||'Agreement updated.');setNote('');router.refresh();}catch(reason){setMessage(reason instanceof Error?reason.message:'Could not update the agreement.');}finally{setBusy('');}}
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),button=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;request({action:button?.value==='submit'?'submit':'save',goal:form.get('goal'),scope:form.get('scope'),deliverables:form.get('deliverables'),outOfScope:form.get('outOfScope'),startDate:form.get('startDate'),targetDate:form.get('targetDate'),milestones:form.get('milestones'),revisionRounds:form.get('revisionRounds'),responseExpectation:form.get('responseExpectation'),clientResponsibilities:form.get('clientResponsibilities'),creatorResponsibilities:form.get('creatorResponsibilities'),finalDelivery:form.get('finalDelivery'),changePolicy:form.get('changePolicy')});}

  if(!agreement&&viewer!=='creator')return <div className="stage-message"><strong>Production agreement not drafted yet.</strong><p>The Studio Partner will set the goal, exact work product, timeline, milestones, review allowance, responsibilities, and final-delivery terms before production begins.</p></div>;
  return <div className="agreement-workspace">
    {agreement&&<div className="agreement-status"><div><span>Agreement v{agreement.version}</span><strong>{agreement.status.replaceAll('_',' ')}</strong></div><p>{agreement.status==='pending_client'?'Client review required.':agreement.status==='changes_requested'?'Studio Partner revision required.':agreement.status==='active'?'Scope and schedule accepted by both parties.':agreement.status==='completed'?'Final delivery accepted and agreement completed.':'Studio Partner draft—not yet binding.'}</p></div>}
    {editable?<form className="agreement-form" onSubmit={submit}>
      <label className="wide"><span>Project goal</span><textarea name="goal" rows={3} maxLength={1500} required defaultValue={current.goal}/></label>
      <label className="wide"><span>Scope of work</span><textarea name="scope" rows={5} maxLength={4000} required defaultValue={current.scope}/></label>
      <label className="wide"><span>Agreed work product / deliverables</span><textarea name="deliverables" rows={5} maxLength={4000} required defaultValue={current.deliverables} placeholder="List each cut, duration, aspect ratio, file type, and included source/project files."/></label>
      <label className="wide"><span>Out of scope</span><textarea name="outOfScope" rows={3} maxLength={2500} defaultValue={current.out_of_scope}/></label>
      <label><span>Production start</span><input name="startDate" type="date" required defaultValue={current.start_date||''}/></label>
      <label><span>Target final delivery</span><input name="targetDate" type="date" required defaultValue={current.target_date||''}/></label>
      <label className="wide"><span>Milestones and review dates</span><textarea name="milestones" rows={5} maxLength={4000} required defaultValue={current.milestones} placeholder="Treatment — date\nFirst review — date\nFinal review — date"/></label>
      <label><span>Included revision rounds</span><input name="revisionRounds" type="number" min="0" max="20" required defaultValue={current.revision_rounds}/></label>
      <label><span>Expected response time</span><input name="responseExpectation" maxLength={500} required defaultValue={current.response_expectation}/></label>
      <label className="wide"><span>Client responsibilities</span><textarea name="clientResponsibilities" rows={3} maxLength={2500} required defaultValue={current.client_responsibilities}/></label>
      <label className="wide"><span>Studio Partner responsibilities</span><textarea name="creatorResponsibilities" rows={3} maxLength={2500} required defaultValue={current.creator_responsibilities}/></label>
      <label className="wide"><span>Final delivery and acceptance</span><textarea name="finalDelivery" rows={3} maxLength={2500} required defaultValue={current.final_delivery}/></label>
      <label className="wide"><span>Change-control policy</span><textarea name="changePolicy" rows={3} maxLength={1500} required defaultValue={current.change_policy}/></label>
      <div className="agreement-notice wide"><strong>Communication method</strong><p>All scope decisions, feedback, files, updates, approvals, and delivery notices stay in this Inchframe Studio project. Outside conversations must be summarized here to become part of the project record.</p></div>
      <div className="review-actions wide"><button className="mini-button" name="action" value="save" disabled={Boolean(busy)} type="submit">{busy==='save'?'Saving…':'Save draft'}</button><button className="mini-button approve" name="action" value="submit" disabled={Boolean(busy)} type="submit">{busy==='submit'?'Sending…':'Send to client for agreement →'}</button></div>
    </form>:agreement&&<AgreementSummary agreement={agreement}/>}
    {agreement&&['pending_client','active'].includes(agreement.status)&&viewer==='client'&&<div className="agreement-decision"><label><span>{agreement.status==='active'?'Reason for scope or schedule amendment':'Approval note or requested change'}</span><textarea value={note} onChange={event=>setNote(event.target.value)} rows={3} maxLength={2000} placeholder={agreement.status==='active'?'Describe the changed scope, work product, schedule, or responsibility.':'Optional when accepting; required when requesting a change.'}/></label><div className="review-actions"><button className="mini-button warn" disabled={Boolean(busy)} onClick={()=>request({action:'changes',note})}>{agreement.status==='active'?'Request recorded amendment':'Request agreement changes'}</button>{agreement.status==='pending_client'&&<button className="mini-button approve" disabled={Boolean(busy)} onClick={()=>request({action:'accept',note})}>Accept scope + timeframe</button>}</div></div>}
    {agreement?.status==='pending_client'&&viewer!=='client'&&<div className="stage-message"><strong>Waiting for client agreement.</strong><p>Production should not begin until the client accepts the scope and timeframe here.</p></div>}
    {message&&<p className={message.includes('Could not')?'form-error':'success-message'} role="status">{message}</p>}
  </div>;
}

function AgreementSummary({agreement}:{agreement:ProjectAgreement}){const rows=[['Goal',agreement.goal],['Scope of work',agreement.scope],['Work product',agreement.deliverables],['Out of scope',agreement.out_of_scope||'None specified.'],['Milestones',agreement.milestones],['Client responsibilities',agreement.client_responsibilities],['Studio Partner responsibilities',agreement.creator_responsibilities],['Final delivery + acceptance',agreement.final_delivery],['Change control',agreement.change_policy]];return <div className="agreement-summary"><div className="agreement-dates"><div><span>Start</span><strong>{agreement.start_date||'Not set'}</strong></div><div><span>Target delivery</span><strong>{agreement.target_date||'Not set'}</strong></div><div><span>Revisions</span><strong>{agreement.revision_rounds} round{agreement.revision_rounds===1?'':'s'}</strong></div><div><span>Response</span><strong>{agreement.response_expectation}</strong></div></div>{rows.map(([label,value])=><div className="agreement-row" key={label}><span>{label}</span><p>{value}</p></div>)}<div className="agreement-notice"><strong>Communication agreement</strong><p>{agreement.communication_method}. All material decisions and approvals must be recorded in this workspace.</p></div></div>}
