import { env } from 'cloudflare:workers';
import type { ChatGPTUser } from '@/app/chatgpt-auth';
export type StudioProject={id:string;owner_id:string;owner_email:string;title:string;project_type:string;status:string;brief:string;audience:string;platforms:string;due_date:string|null;aspect_ratios:string;style_notes:string;budget_range:string;created_at:string;updated_at:string};
export type StudioAsset={id:string;project_id:string;uploaded_by_id:string;uploaded_by_email:string;kind:string;object_key:string;filename:string;mime_type:string;byte_size:number;label:string;version:number;status:string;created_at:string};
export type StudioComment={id:string;project_id:string;asset_id:string|null;author_id:string;author_email:string;body:string;created_at:string};
let schemaReady=false;
function database(){if(!env.DB)throw new Error('Studio database is unavailable.');return env.DB;}
export async function ensureSchema(){if(schemaReady)return;const db=database();await db.batch([
db.prepare(`CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, owner_email TEXT NOT NULL, title TEXT NOT NULL, project_type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'intake_received', brief TEXT NOT NULL, audience TEXT NOT NULL DEFAULT '', platforms TEXT NOT NULL DEFAULT '', due_date TEXT, aspect_ratios TEXT NOT NULL DEFAULT '[]', style_notes TEXT NOT NULL DEFAULT '', budget_range TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`),
db.prepare(`CREATE TABLE IF NOT EXISTS assets (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, uploaded_by_id TEXT NOT NULL, uploaded_by_email TEXT NOT NULL, kind TEXT NOT NULL, object_key TEXT NOT NULL UNIQUE, filename TEXT NOT NULL, mime_type TEXT NOT NULL, byte_size INTEGER NOT NULL, label TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'uploaded', created_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE)`),
db.prepare(`CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, asset_id TEXT, author_id TEXT NOT NULL, author_email TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE CASCADE)`),
db.prepare(`CREATE TABLE IF NOT EXISTS decisions (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, asset_id TEXT NOT NULL, author_id TEXT NOT NULL, author_email TEXT NOT NULL, decision TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE CASCADE)`),
db.prepare('CREATE INDEX IF NOT EXISTS idx_projects_owner_updated ON projects(owner_id, updated_at DESC)'),db.prepare('CREATE INDEX IF NOT EXISTS idx_assets_project_created ON assets(project_id, created_at DESC)'),db.prepare('CREATE INDEX IF NOT EXISTS idx_comments_project_asset ON comments(project_id, asset_id, created_at)'),db.prepare('CREATE INDEX IF NOT EXISTS idx_decisions_asset_created ON decisions(asset_id, created_at DESC)')]);await db.prepare('PRAGMA optimize').run();schemaReady=true;}
export function isStudioAdmin(email:string){const configured=process.env.STUDIO_ADMIN_EMAILS??'info@inchframe.com';return configured.split(',').map(v=>v.trim().toLowerCase()).filter(Boolean).includes(email.toLowerCase());}
export async function createProject(user:ChatGPTUser,input:{title:string;projectType:string;brief:string;audience:string;platforms:string;dueDate:string|null;aspectRatios:string[];styleNotes:string;budgetRange:string}){await ensureSchema();const id=crypto.randomUUID(),now=new Date().toISOString();await database().prepare(`INSERT INTO projects (id,owner_id,owner_email,title,project_type,status,brief,audience,platforms,due_date,aspect_ratios,style_notes,budget_range,created_at,updated_at) VALUES (?,?,?,?,?,'intake_received',?,?,?,?,?,?,?,?,?)`).bind(id,user.userId,user.email,input.title,input.projectType,input.brief,input.audience,input.platforms,input.dueDate,JSON.stringify(input.aspectRatios),input.styleNotes,input.budgetRange,now,now).run();return id;}
export async function listProjects(user:ChatGPTUser){await ensureSchema();const q=isStudioAdmin(user.email)?database().prepare('SELECT * FROM projects ORDER BY updated_at DESC'):database().prepare('SELECT * FROM projects WHERE owner_id=? ORDER BY updated_at DESC').bind(user.userId);return(await q.all<StudioProject>()).results;}
export async function getProjectForUser(projectId:string,user:ChatGPTUser){await ensureSchema();const project=await database().prepare('SELECT * FROM projects WHERE id=?').bind(projectId).first<StudioProject>();return project&&(project.owner_id===user.userId||isStudioAdmin(user.email))?project:null;}
export async function getProjectBundle(projectId:string,user:ChatGPTUser){const project=await getProjectForUser(projectId,user);if(!project)return null;const[a,c]=await Promise.all([database().prepare('SELECT * FROM assets WHERE project_id=? ORDER BY created_at DESC').bind(projectId).all<StudioAsset>(),database().prepare('SELECT * FROM comments WHERE project_id=? ORDER BY created_at ASC').bind(projectId).all<StudioComment>()]);return{project,assets:a.results,comments:c.results};}
export async function addAsset(user:ChatGPTUser,projectId:string,input:{kind:string;objectKey:string;filename:string;mimeType:string;byteSize:number;label:string}){await ensureSchema();const id=crypto.randomUUID(),now=new Date().toISOString();const v=await database().prepare('SELECT COALESCE(MAX(version),0) max_version FROM assets WHERE project_id=? AND kind=?').bind(projectId,input.kind).first<{max_version:number}>();const status=input.kind==='seed'?'uploaded':'in_review';await database().prepare('INSERT INTO assets (id,project_id,uploaded_by_id,uploaded_by_email,kind,object_key,filename,mime_type,byte_size,label,version,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,projectId,user.userId,user.email,input.kind,input.objectKey,input.filename,input.mimeType,input.byteSize,input.label,(v?.max_version??0)+1,status,now).run();await database().prepare('UPDATE projects SET updated_at=?,status=? WHERE id=?').bind(now,input.kind==='seed'?'intake_received':'client_review',projectId).run();return id;}
export async function getAssetForUser(assetId:string,user:ChatGPTUser){await ensureSchema();return(await database().prepare('SELECT a.* FROM assets a JOIN projects p ON p.id=a.project_id WHERE a.id=? AND (p.owner_id=? OR ?=1)').bind(assetId,user.userId,isStudioAdmin(user.email)?1:0).first<StudioAsset>())??null;}
export async function addComment(user:ChatGPTUser,projectId:string,assetId:string|null,body:string){await ensureSchema();const now=new Date().toISOString();await database().prepare('INSERT INTO comments (id,project_id,asset_id,author_id,author_email,body,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),projectId,assetId,user.userId,user.email,body,now).run();await database().prepare('UPDATE projects SET updated_at=? WHERE id=?').bind(now,projectId).run();}
export async function recordDecision(user:ChatGPTUser,projectId:string,assetId:string,decision:'approved'|'changes_requested',note:string){await ensureSchema();const now=new Date().toISOString();const db=database();await db.batch([db.prepare('INSERT INTO decisions (id,project_id,asset_id,author_id,author_email,decision,note,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),projectId,assetId,user.userId,user.email,decision,note,now),db.prepare('UPDATE assets SET status=? WHERE id=? AND project_id=?').bind(decision,assetId,projectId),db.prepare('UPDATE projects SET updated_at=?,status=? WHERE id=?').bind(now,decision==='approved'?'approval_recorded':'revisions_requested',projectId)]);}
