import Link from 'next/link';
import type { Metadata } from 'next';
import { requireChatGPTUser } from '@/app/chatgpt-auth';
import { PortalHeader } from '@/components/PortalHeader';
import { listProjects,isStudioAdmin } from '@/lib/data';
import { shortDate,titleCase } from '@/lib/format';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Client projects'};
export default async function PortalPage(){const user=await requireChatGPTUser('/portal');const projects=await listProjects(user);const admin=isStudioAdmin(user.email);return <main className="portal-page"><PortalHeader user={user}/><section className="portal-head"><div className="shell portal-title-row"><div><p className="eyebrow"><span>●</span> {admin?'Studio production desk':'Client area'}</p><h1>{admin?'All productions':'Your projects'}</h1><p>{admin?'Review active client work, upload versions, and keep approvals moving.':'Briefs, seed images, reviews, decisions, and delivery in one place.'}</p></div><Link className="button button-green" href="/start">New project +</Link></div></section><section className="portal-content"><div className="shell">{projects.length===0?<div className="empty-state"><span>00</span><h2>No projects yet.</h2><p>Start with a brief and a few visual seeds. Your production will appear here.</p><Link className="button button-green" href="/start">Start a project</Link></div>:<div className="project-list">{projects.map((project,index)=><Link className="project-row" href={`/portal/projects/${project.id}`} key={project.id}><span className="project-number">{String(index+1).padStart(2,'0')}</span><div className="project-main"><span>{titleCase(project.project_type)}</span><h2>{project.title}</h2>{admin&&<small>{project.owner_email}</small>}</div><div className="project-meta"><span className={`status ${project.status}`}>{titleCase(project.status)}</span><small>Updated {shortDate(project.updated_at)}</small></div><b aria-hidden="true">→</b></Link>)}</div>}</div></section></main>}
