import Link from 'next/link';
import type { Metadata } from 'next';
import { requireChatGPTUser } from '@/app/chatgpt-auth';
import { PortalHeader } from '@/components/PortalHeader';
import { listProjects,isStudioAdmin } from '@/lib/data';
import { shortDate,titleCase } from '@/lib/format';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Client projects'};
export default async function PortalPage(){const user=await requireChatGPTUser('/portal');const projects=await listProjects(user);const admin=isStudioAdmin(user);return <main className="portal-page"><PortalHeader user={user}/><section className="portal-head"><div className="shell portal-title-row"><div><p className="eyebrow"><span>●</span> {admin?'Studio production desk':'Client area'}</p><h1>{admin?'All inquiries + productions':'Your projects'}</h1><p>{admin?'Review new inquiries, issue project access, and keep production approvals moving.':'Track your inquiry, unlock accepted projects, add media, review versions, and approve delivery.'}</p></div>{!admin&&<Link className="button button-green" href="/start">New inquiry +</Link>}</div></section><section className="portal-content"><div className="shell">{projects.length===0?<div className="empty-state"><span>00</span><h2>{admin?'No inquiries yet.':'No projects yet.'}</h2><p>{admin?'New verified customer inquiries will appear here.':'Send a short inquiry—no invitation code or uploads required.'}</p>{!admin&&<Link className="button button-green" href="/start">Start an inquiry</Link>}</div>:<div className="project-list">{projects.map((project,index)=><Link className="project-row" href={`/portal/projects/${project.id}`} key={project.id}><span className="project-number">{String(index+1).padStart(2,'0')}</span><div className="project-main"><span>{titleCase(project.project_type)}</span><h2>{project.title}</h2>{admin&&<small>{project.owner_email}</small>}</div><div className="project-meta"><span className={`status ${project.status}`}>{titleCase(project.status)}</span><small>Updated {shortDate(project.updated_at)}</small></div><b aria-hidden="true">→</b></Link>)}</div>}</div></section></main>}
