import Link from 'next/link';
import type { Metadata } from 'next';
import { requireChatGPTUser } from '@/app/chatgpt-auth';
import { PortalHeader } from '@/components/PortalHeader';
import { CreatorReviewControls } from '@/components/CreatorReviewControls';
import { isStudioAdmin,listCreatorApplications } from '@/lib/data';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Creator network'};
function money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value)}
export default async function PortalCreatorsPage(){const user=await requireChatGPTUser('/portal/creators');const admin=isStudioAdmin(user),profiles=await listCreatorApplications(user);return <main className="portal-page"><PortalHeader user={user}/><section className="portal-head"><div className="shell portal-title-row"><div><p className="eyebrow"><span>●</span> Inchframe production network</p><h1>{admin?'Creator applications':'Creator certification'}</h1><p>{admin?'Verify Paid Pro membership, identity, and tax/payout readiness before publishing approved profiles.':'Manage your application to join Inchframe-led productions as an independent subcontractor.'}</p></div>{!admin&&<Link className="button button-green" href="/creators/apply">{profiles.length?'Edit application':'Apply now'} →</Link>}</div></section><section className="portal-content"><div className="shell">{profiles.length===0?<div className="empty-state"><span>00</span><h2>{admin?'No creator applications yet.':'No application yet.'}</h2><p>{admin?'Paid Pro creator applications will appear here.':'Active Paid Pro creators can submit a production profile for review.'}</p>{!admin&&<Link className="button button-green" href="/creators/apply">Start application</Link>}</div>:<div className="creator-admin-list">{profiles.map(profile=><article className="portal-card creator-admin-card" key={profile.id}><img src={`/api/creator-icons/${profile.id}`} alt=""/><div><div className="card-heading"><div><span>{profile.status.toUpperCase()}</span><h2>{profile.display_name}</h2></div></div><strong>{profile.headline}</strong><p>{profile.bio}</p><div className="creator-admin-meta"><span>{profile.owner_email}</span><span>Pro email: {profile.inchframe_email}</span><span>{money(profile.rate_min)}–{money(profile.rate_max)} / {profile.rate_unit}</span><span>{profile.location}</span></div><div className="sample-list compact">{profile.samples.map(sample=><a href={sample.url} target="_blank" rel="noreferrer nofollow" key={sample.id}><strong>{sample.title}</strong><b>↗</b></a>)}</div>{admin?<CreatorReviewControls id={profile.id} status={profile.status} proVerified={profile.pro_verified===1} identityVerified={profile.identity_verified===1} taxVerified={profile.tax_verified===1}/>:profile.status==='approved'?<Link className="button button-small button-outline" href={`/creators/${profile.slug}`}>View public profile →</Link>:<p className="stage-message">Studio review status: <strong>{profile.status}</strong>. Updating the profile returns it to review.</p>}</div></article>)}</div>}</div></section></main>}
